In [7]:
L3 = [True, "2", 3.0, 4]
[type(i) for i in L3]

[bool, str, float, int]

import array

L = list(range(10))
A = array.array('i', L)
A

In [ ]:
#### multidimensional arrays

In [27]:
import numpy as np

z = np.array([[1,2,3], [4,5,6]])
print(z)


[[1 2 3]
 [4 5 6]]


In [28]:
z2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(z2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
x3 = np.random.randint(10, size = (3,4))
print(x3)

[[4 8 5 8]
 [7 3 6 6]
 [6 8 7 4]]


In [38]:
x4 = np.random.randint(10, size = (3,4,5))
print(x4)

[[[9 8 1 9 5]
  [2 0 6 4 4]
  [9 3 8 0 8]
  [7 1 0 9 7]]

 [[3 3 2 4 1]
  [4 8 7 8 6]
  [9 3 2 0 7]
  [8 7 8 3 1]]

 [[1 5 0 3 2]
  [5 6 3 1 0]
  [9 9 3 9 1]
  [5 5 4 0 3]]]


In [ ]:
##### random : values are truly random, gives you random value every trime you run
#### Random seed: to get reproducible value, gives you same value every time you run.

In [43]:
np.random.random((3,3))

array([[0.43887533, 0.62372945, 0.23446052],
       [0.97121293, 0.3017997 , 0.05952466],
       [0.28855408, 0.48621916, 0.60669297]])

In [47]:
np.random.seed(100)
np.random.random((3,3))

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659]])

In [48]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#### Indexing arrays

In [50]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [52]:
print(x1[0])
print(x1[4])
print(x1[-1])

5
7
9


In [53]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [54]:
x2[2,3]

7

In [55]:
x2[1,0]

7

In [56]:
x2[1,1]

6

In [97]:
### Slicing arrays - lot like slicing lists , with a couple additionsOne- dimensional arrays are the exact same.

In [99]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#### multiple-dimensional subarrays:  same as one-dimensional arrays, but with a comma seperating elements

In [62]:
import numpy as np

np.random.seed(0)
x2 = np.random.randint(10, size =(3,4))
print(x2)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [63]:
x2[:2, :3]

array([[5, 0, 3],
       [7, 9, 3]])

In [65]:
x2[0, :2]

array([5, 0])

In [66]:
np.random.seed(1)
j = np.random.randint(10, size =(3,4))
j

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [68]:
print(j[1,1:3])

[0 1]


In [69]:
print(j[2, :3])

[6 9 2]


In [70]:
print(j[0:2, 1:])

[[8 9 5]
 [0 1 7]]


In [71]:
print(j[:,0:1])

[[5]
 [0]
 [6]]


In [ ]:
### views and copies of arrays

- subarrays as no-copy views: slices(subarrays) are not copies of your array they're view.
- this means if you alter the arrays, it will alter the original.

In [ ]:
### Reshaping arrays - reshape method allows arrrays to be reshaped

In [102]:
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [103]:
grid = array.reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
we can also reshape a one-dimensional array into a multidimensional 2-d row or column matrix
notice the extra [] in the output

In [75]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [76]:
x.reshape((1,3))

array([[1, 2, 3]])

In [77]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [78]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [79]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [81]:
x = np.array([1, 2, 3])
print(x2)
x[:, np.newaxis]

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[1],
       [2],
       [3]])

In [83]:
x2[np.newaxis, :]

array([[[5, 0, 3, 3],
        [7, 9, 3, 5],
        [2, 4, 7, 6]]])

In [ ]:
###  challenge - create a random rX4 array

In [84]:
np.random.seed(0)
x = np.random.randint(5, size =(4, 4))
x

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4],
       [2, 1, 0, 1]])

In [ ]:
### change the value of the 2nd of the 3rd value doesn't matter)

In [90]:
x[2, 1]  = 5
x

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 5, 0, 4],
       [2, 1, 0, 1]])

In [ ]:
### change to the value of the 4th value of the 2nd array (value doesn't matter)

In [91]:
x[1, 3] = 6
x

array([[4, 0, 3, 3],
       [3, 1, 3, 6],
       [4, 5, 0, 4],
       [2, 1, 0, 1]])

In [ ]:
## create a copy of the third array

In [92]:
x_copy = x[2]. copy()
x_copy

array([4, 5, 0, 4])

In [ ]:
## Reshape the array into a coulumn vector

In [95]:
x_copy.reshape((4, 1))

array([[4],
       [5],
       [0],
       [4]])

In [ ]:
#### Concatenation + means joining into one array.

In [108]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x ,y])

array([1, 2, 3, 4, 5, 6])

In [109]:
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
##  we  can also stack arrays of mixed dimensions

vstack = verticle arrays
hstack = horizontal arrays

In [114]:
x = np.array([7, 8 ,9])
np.vstack([x, grid])

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [115]:
np.vstack([x, x, x, grid, grid])

array([[7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
y =np.array([[99],
            [99]])

np.hstack([grid, y])
            

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [ ]:
## Splitting arrays = opposite of concatenation
    We use np.split()
    pass the array and the indices to split

- we can also split verically or horizontally


In [122]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2 = np.split(x, [3])
print(x1, x2)

[0 1 2] [3 4 5 6 7 8 9]


In [123]:
x3, x4, x5 = np.split(x, [3, 5])
print(x3, x4, x5)

[0 1 2] [3 4] [5 6 7 8 9]


In [124]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, x4, x5 = np.split(x, [2, 4, 5, 7])
print(x1, x2, x3, x4, x5)
                              

[0 1] [2 3] [4] [5 6] [7 8 9]


In [128]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [129]:
upper, lower =np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [130]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
## Ufuncs
conduction analyses on arrays can be surprisingly difficult - and slow
Numpy provides vectorized operations through universal functions, or ufuncs
Because Python is flexible - as we've discussed previously- as its core it is not very fast
Techinically, because of how it is intepreted it can not be complied very  efficiently, like some other languages
lets see how slow loops  can be by computing reciprocals two days.

In [131]:
import numpy as np

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
compute_reciprocals(values)

[6 9 5 4 1]


array([0.16666667, 0.11111111, 0.2       , 0.25      , 1.        ])

In [142]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.62 s ± 37.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [149]:
print(compute_reciprocals(values))
print(1.0 / values)
%timeit (1.0 / big_array)

[0.16666667 0.11111111 0.2        0.25       1.        ]
[0.16666667 0.11111111 0.2        0.25       1.        ]
5.95 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
When Python runs a loop on an array, it checks the type of each element and looks up whtat function to use for that type of variable


In [ ]:
In a compiled language, the target machine directly translates the program. In an interpreted language, the source code is not directly translated by the target machine. Instead, a different program, aka the interpreter, reads and executes the code.

- compiled languages: converted directly into machine code that the processor  can execute.
                    - faster and more efficient than interpreted languages
example of complied languages: C, C++, Erlang, Haskell, Rust, and Go

- interpreted langueages: rus through program line by and exacute each command
 Example: PHP, Ruby, Python, and JavaScript.


In [ ]:
## Fancy Indexing

In [150]:
import numpy as np
rand=np.random.RandomState(42)

x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [151]:
print(x[0])
print(x[-1])
print(x[5:])

51
74
[20 82 86 74 74]


In [152]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [154]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [155]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])